config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => "homes#top"
    resources :orders, only: [:show,]
    resources :items, only: [:new, :show, :index, :edit, :create, :update]
    resources :customers, only: [:show, :index, :edit,:update]

  end

  scope module: :public do
    root to: 'homes#top'
    post 'orders/confirmation' => "orders#confirmation"
    get 'orders/completion' => "orders#completion"
    resources :orders, only: [:show, :index, :new, :create]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    get '/customers/show' => "customers#show"
    get '/customers/information/edit' => "customers#edit"
    patch '/customers/information' => "customers#update"
    get 'customers/unsubscribe' => "customers#unsubscribe"
    patch 'customers/withdrawal' => "customers#withdrawal"
    get '/about' => "homes#about"

    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
   has_many :cart_items
   has_many :order_products
   has_one_attached :image


    def with_tax_price
     (price * 1.1).ceil
    end



 def get_image(width, height)
          unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
          end
     image
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
  @item = Item.new(item_params)
   if @item.save
   redirect_to admin_item_path(@item.id)
   else
    @item = Item.all
       render :index
   end
  end

  def index
   @item = Item.new
   @items = Item.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_items_path(@item.id)
    else
        render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">

<h1>商品編集</h1>
  <%= form_with model: @item,url:admin_item_path do |f| %>

    <h4>商品画像</h4>　　<%= f.file_field :image, accept: "image/*" %>

    <h4>商品名</h4>　　<%= f.text_field :name %>

    <h4>商品説明</h4>　  <%= f.text_area :introduction %>

    <h4>税抜価格</h4>　　<%= f.text_field :price %>
    <%= f.submit '変更を保存' %>
  <% end %>

  </div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
 <h1 class="col-md-6">商品一覧</h1>
 <%= link_to '新規登録', new_admin_item_path, class: "btn btn-sm btn-danger col-md-3 offset-md-3" %>

<table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
    </tr>
 </thead>

<tbody>
<% @items.each do |item| %>
<tr>
<td>
<%= item.id %>
</td>
<td>
<%= link_to admin_item_path(item.id) do %>
<%= item.name %>
<% end %>
</td>
<td>
<%= item.price %>
<% end %>
</td>
</tr>
</tbody>
</table>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">

<h1>商品新規登録</h1>
  <%= form_with model: @item,url:admin_items_path do |f| %>

    <h4>商品画像</h4>　　<%= f.file_field :image, accept: "image/*" %>

    <h4>商品名</h4>　　<%= f.text_field :name %>

    <h4>商品説明</h4>　  <%= f.text_area :introduction %>

    <h4>税抜価格</h4>　　<%= f.text_field :price %>
    <%= f.submit '新規登録' %>
  <% end %>

  </div>

app/views/admin/items/show.html.erb
<div class="container">
<h2>商品詳細</h2>

<p><%= image_tag @item.get_image(100, 100) %></p>


<h2><%= @item.name %></h2>

<h2><%= @item.introduction %></h2>

<p><%= @item.price %></p>

<%= link_to edit_admin_item_path(@item.id) do %>
　<p>編集する</p>
　<% end %>

</div>