config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => "homes#top"
    resources :orders, only: [:show,]
    resources :items, only: [:new, :show, :index, :edit, :create, :update]
    resources :customers, only: [:show, :index, :edit,:update]

  end

  scope module: :public do
    root to: 'homes#top'
    post 'orders/confirmation' => "orders#confirmation"
    get 'orders/completion' => "orders#completion"
    resources :orders, only: [:show, :index, :new, :create]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    get '/customers/show' => "customers#show"
    get '/customers/information/edit' => "customers#edit"
    patch '/customers/information' => "customers#update"
    get 'customers/unsubscribe' => "customers#unsubscribe"
    patch 'customers/withdrawal' => "customers#withdrawal"
    get '/about' => "homes#about"

    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :cart_items
has_many :orders
has_one_attached :image


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
     redirect_to admin_customer_path(@customer.id)
   else
     render :edit
   end
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h2>会員情報編集</h2>
<p>会員ID <%= @customer.id %></p>
<% if @customer.errors.any? %>
    <div>
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_with model: @customer,url:admin_customer_path(@customer.id), method: :patch do |f| %>
    <div class="field">
      <%= f.label :姓 %><br />
      <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
    </div>

    <div class="field">
      <%= f.label :名 %><br />
      <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
    </div>


    <div class="field">
      <%= f.label :姓カナ %><br />
      <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
    </div>

    <div class="field">
      <%= f.label :名カナ %><br />
      <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
    </div>

    <div class="field">
      <%= f.label :郵便番号（ハイフンなし） %><br />
      <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
    </div>

    <div class="field">
      <%= f.label :住所 %><br />
      <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
    </div>

    <div class="field">
      <%= f.label :電話番号（ハイフンなし） %><br />
      <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
    </div>

    <div class="field">
      <%= f.label :メールアドレス %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="actions">
    <%= f.submit "変更を保存" %>
    </div>
  <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="container">

<h1>会員一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
 </thead>

<tbody>
<% @customers.each do |customers| %>
<tr>
<td>
<%= customers.id %>
</td>
<td>
<%= link_to admin_customer_path(customers.id) do %>
<%= customers.last_name %> <%= customers.first_name%>
<% end %>
</td>
<td>
<%= customers.email %>
</td>
<td>
<%if customers.is_deleted %>
<h4>退会</h4>
<% else %>
<h4>有効</h4>
<% end %>
</td>
<% end %>
</tr>
</tbody>
</table>
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <h2>会員詳細</h2>

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>カナ</th>
      <th>郵便番号</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td>
      <%= @customer.id %>
   </td>
    <td>
      <%= @customer.last_name %> <%= @customer.first_name %>
   </td>
    <td>
      <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
    </td>
   <td>
      <%= @customer.postal_code %>
   </td>
   <td>
      <%= @customer.address %>
   </td>
   <td>
      <%= @customer.telephone_number %>
   </td>
    <td>
      <%= @customer.email %>
   </td>
      <td>
   <%if @customer.is_deleted %>
      <h4>退会</h4>
      <% else %>
      <h4>有効</h4>
      <% end %>
      </td>
  </tr>
  </tbody>
</table>

<%= link_to admin_path do %>
<p>注文履歴一覧を見る</p>
<% end %>

<%= link_to edit_admin_customer_path do %>
<p>編集する</p>
<% end %>

</div>