config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => "homes#top"
    resources :orders, only: [:show,]
    resources :items, only: [:new, :show, :index, :edit, :create, :update]
    resources :customers, only: [:show, :index, :edit,:update]

  end

  scope module: :public do
    root to: 'homes#top'
    post 'orders/confirmation' => "orders#confirmation"
    get 'orders/completion' => "orders#completion"
    resources :orders, only: [:show, :index, :new, :create]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    get '/customers/show' => "customers#show"
    get '/customers/information/edit' => "customers#edit"
    patch '/customers/information' => "customers#update"
    get 'customers/unsubscribe' => "customers#unsubscribe"
    patch 'customers/withdrawal' => "customers#withdrawal"
    get '/about' => "homes#about"

    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">

<h1>注文履歴一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
    </tr>
 </thead>

<tbody>
<% @orders.each do |orders| %>
<tr>
<td>
<%= link_to admin_order_path(orders.id) do %>
<%= orders.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %>
<% end %>
</td>
<td>
<%= orders.name %>
</td>
<td>
<%= orders.order_products.sum(:quantity) %>
<% end %>
</td>
</tr>
</tbody>
</table>
<%= paginate @orders %>
</div>