config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    get '/' => "homes#top"
    resources :orders, only: [:show,]
    resources :items, only: [:new, :show, :index, :edit, :create, :update]
    resources :customers, only: [:show, :index, :edit,:update]

  end

  scope module: :public do
    root to: 'homes#top'
    post 'orders/confirmation' => "orders#confirmation"
    get 'orders/completion' => "orders#completion"
    resources :orders, only: [:show, :index, :new, :create]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    get '/customers/show' => "customers#show"
    get '/customers/information/edit' => "customers#edit"
    patch '/customers/information' => "customers#update"
    get 'customers/unsubscribe' => "customers#unsubscribe"
    patch 'customers/withdrawal' => "customers#withdrawal"
    get '/about' => "homes#about"

    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :cart_items
has_many :orders
has_one_attached :image


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/item.rb
class Item < ApplicationRecord
   has_many :cart_items
   has_many :order_products
   has_one_attached :image


    def with_tax_price
     (price * 1.1).ceil
    end



 def get_image(width, height)
          unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
          end
     image
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products

  enum method_of_payment: { credit_card: 0, transfer: 1 }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :item

    def subtotal
     purchase_price * quantity
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
     redirect_to admin_customer_path(@customer.id)
   else
     render :edit
   end
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
  @item = Item.new(item_params)
   if @item.save
   redirect_to admin_item_path(@item.id)
   else
    @item = Item.all
       render :index
   end
  end

  def index
   @item = Item.new
   @items = Item.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_items_path(@item.id)
    else
        render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
# def new

# end

#   # POST /resource/sign_in
# def create
#   #   super
# end

#   # DELETE /resource/sign_out
# def destroy

# end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
        admin_path
    else
        root_path
    end
  end

   def after_sign_out_path_for(resource)
    if  resource == :admin
        new_admin_session_path
    else
        root_path
    end
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


 <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "LOGO", root_path, class: 'nav-link text-light' %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if customer_signed_in? %>

           <li class="nav-item">
              <%= link_to customers_show_path(current_customer),  class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>マイページ
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>商品一覧
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to cart_items_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>カート
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>

            <% elsif admin_signed_in? %>
             <li class="nav-item">
              <%= link_to admin_items_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>商品一覧
              <% end %>
            </li>

             <li class="nav-item">
              <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>会員一覧
              <% end %>
            </li>

             <li class="nav-item">
              <%= link_to admin_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>注文履歴一覧
              <% end %>
            </li>

             <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>

            <% else %>


            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i>About
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to items_path,  class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>商品一覧
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to  new_customer_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>

     <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>